openapi: 3.0.1
info:
  title: DBCO App - Backend to GGD Interface
  description: |
    This specification describes the interface between the DBCO app backend and the GGD middleware.    
  contact:
    name: Ministerie van Volksgezondheid Welzijn en Sport coordination repository
    url: https://github.com/minvws/nl-covid19-dbco-app-coordination
  license:
    name: European Union Public License v. 1.2
    url: https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt
  version: 0.1.0
servers:
  - url: https://tbd.example.com/v1
tags:
  - name: Tasks
    description: |
      Retrieving tasks
  - name: Contacts
    description: |
      Delivering contacts
paths:
  /tasks:
    get:
      tags:
        - Tasks
      summary: Get a generic set of tasks that is user independent.
      description: |
         Get the list of tasks that can be used for all users. This will not be fetched on a per-user basis but only a few times per day, as it is fairly static data that doesn't change often.
      operationId: getTasks
      responses:
        200:
          description: Tasks retrieved succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'
  /tasks/{caseId}:
    get:
      tags:
        - Tasks
      summary: Get a user specific set of tasks that is user independent.
      description: |
         Get the list of tasks for a specicic BCO case. This will be fetched on a per-user basis.
      parameters:
        - name: caseId
          in: path
          description: caseId to retrieve the tasks for
          required: true
          schema:
            type: string
      operationId: getTasksByCase
      responses:
        200:
          description: Tasks retrieved succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'
  /contacts/{caseId}:
    post:
      tags:
        - Contacts
      summary: Post the contacts to the GGD backend
      description: |
        All contacts will be updated every time this method is called. The GGD should replace any contacts that have the same identifier.
        The response will be entirely encrypted with a public key. This is not reflected in the swagger docs to keep the objects readable.      
      parameters:
        - name: caseId
          in: path
          description: caseId that these contacts belong to
          required: true
          schema:
            type: string
      operationId: postContacts
      responses:
        204:
          description: Contacts updated succesfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListRequest'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: A unique id for this task. Used to be able to relate contacts to a task.
          example: 123e4567-e89b-12d3-a456-426614172000
        taskType:
          type: string
          description: currently. only 'contact' tasks are supported, which instruct the user to collect one or more contacts
          example: contact
        name:
          type: string
          description: The (short) name of the task.
          example: The goalkeeper of your football match
        description:
          type: string
          description: The optional (longer) explanation of the task. 
          example: You indicated you hugged the goalkeeper after that score, please provide contact details
      required: 
        - taskType
        - name
    Contact:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: a unique id for this contact. Generated by the device. If a user updates a contact later, this id will be preserved so that the data can be updated.
          example: 123e4567-e89b-12d3-a456-426614174000
        lastModified:
          type: string
          format: date-time
          description: | 
            The moment this contact was last modified. (Note: this is device generated so may be off due to clock skew, however future updates would have the same skew, so the date can still be used to see that an item was modified)
          example: 2017-07-21T17:32:28Z
        taskId: 
          type: string
          format: uuid
          description: The task that lead to this contact. If the user provides contacts outside the scope of a contact request (e.g. additional contacts), the taskId will be null.
          example: 123e4567-e89b-12d3-a456-426614172000
        firstName:
          type: string
          description: The first name of the contact
          example: John
        lastName:
          type: string
          description: The last name of the contact
          example: Doe
        phoneNumber: 
          type: string
          description: The phone number of the contact
          example: +31612345678
        email: 
          type: string
          format: email
          description: The email address of the contact
          example: john@doe.com
        bsn:
          type: string
          description: The social security number of the contact
          example: 123456789
      required: 
        - id
        - lastModified
        - firstName
        - lastName
    TaskListResponse:
      type: array
      items:
        $ref: '#/components/schemas/Task'
    ContactListRequest:
      type: array
      items: 
        $ref: '#/components/schemas/Contact'
      